import React from "react";
import {
  HiOutlineShieldCheck,
  HiOutlineExclamationTriangle,
  HiOutlineXCircle,
  HiOutlineHeart,
  HiOutlineClipboardDocumentCheck,
  HiOutlineBell,
} from "react-icons/hi2";

const riskConfig = {
  "Low Risk": {
    color: "from-emerald-500 to-green-600",
    bg: "bg-emerald-500/10",
    border: "border-emerald-500/30",
    text: "text-emerald-400",
    icon: HiOutlineShieldCheck,
    badge: "bg-emerald-500/20 text-emerald-300 ring-emerald-500/30",
    recommendation: "Continue regular check-ups. Maintain a healthy lifestyle with balanced diet and exercise.",
    confidence: "The model indicates a low probability of hospital readmission within 30 days.",
  },
  "Medium Risk": {
    color: "from-amber-500 to-orange-600",
    bg: "bg-amber-500/10",
    border: "border-amber-500/30",
    text: "text-amber-400",
    icon: HiOutlineExclamationTriangle,
    badge: "bg-amber-500/20 text-amber-300 ring-amber-500/30",
    recommendation: "Schedule follow-up visits. Monitor blood sugar levels closely and review medication adherence.",
    confidence: "The model indicates a moderate probability of hospital readmission. Close monitoring is advised.",
  },
  "High Risk": {
    color: "from-red-500 to-rose-600",
    bg: "bg-red-500/10",
    border: "border-red-500/30",
    text: "text-red-400",
    icon: HiOutlineXCircle,
    badge: "bg-red-500/20 text-red-300 ring-red-500/30",
    recommendation: "Immediate clinical attention recommended. Conduct comprehensive diabetes management review and consider care coordination.",
    confidence: "The model indicates a high probability of hospital readmission within 30 days. Urgent intervention suggested.",
  },
};

export default function ResultCard({ prediction }) {
  const config = riskConfig[prediction] || riskConfig["Low Risk"];
  const Icon = config.icon;

  return (
    <div className={`glass-card p-6 sm:p-8 ${config.border} border animate-in fade-in duration-500`}>
      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${config.color} flex items-center justify-center shadow-lg`}>
          <Icon className="w-6 h-6 text-white" />
        </div>
        <div>
          <h3 className="text-white font-semibold text-lg">Prediction Result</h3>
          <p className="text-slate-400 text-sm">AI-powered risk assessment</p>
        </div>
      </div>

      {/* Risk Badge */}
      <div className="flex justify-center mb-6">
        <span className={`inline-flex items-center gap-2 px-5 py-2.5 rounded-full text-lg font-bold ring-1 ${config.badge}`}>
          <Icon className="w-5 h-5" />
          {prediction}
        </span>
      </div>

      {/* Info Cards */}
      <div className="space-y-4">
        {/* Confidence */}
        <div className={`${config.bg} rounded-xl p-4 border ${config.border}`}>
          <div className="flex items-start gap-3">
            <HiOutlineClipboardDocumentCheck className={`w-5 h-5 mt-0.5 ${config.text} flex-shrink-0`} />
            <div>
              <p className="text-sm font-medium text-white mb-1">Assessment</p>
              <p className="text-sm text-slate-300 leading-relaxed">{config.confidence}</p>
            </div>
          </div>
        </div>

        {/* Recommendation */}
        <div className="bg-white/5 rounded-xl p-4 border border-white/10">
          <div className="flex items-start gap-3">
            <HiOutlineHeart className="w-5 h-5 mt-0.5 text-cyan-400 flex-shrink-0" />
            <div>
              <p className="text-sm font-medium text-white mb-1">Recommendation</p>
              <p className="text-sm text-slate-300 leading-relaxed">{config.recommendation}</p>
            </div>
          </div>
        </div>

        {/* Disclaimer */}
        <div className="flex items-start gap-2 pt-2">
          <HiOutlineBell className="w-4 h-4 text-slate-500 mt-0.5 flex-shrink-0" />
          <p className="text-xs text-slate-500 leading-relaxed">
            This prediction is generated by an ML model trained on historical hospital data. 
            It should be used as a decision-support tool and not as a definitive clinical diagnosis.
          </p>
        </div>
      </div>
    </div>
  );
}
